const concentric = [
  {
    img: 'assets/img/card/snayp/k-20sm-2-b.jpg',
    alt: 'снайперка / концентрическая 20 сантиметров',
    title: 'снайперка 20',
    size: '20см',
    weight: '~400 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },

  {
    img: 'assets/img/card/omega/20sm-b.jpg',
    alt: 'снайперка / концентрическая 20 сантиметров',
    title: 'снайперка 20-2',
    size: '20см',
    weight: '~500 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-24x12sm.jpg',
    alt: 'снайперка / концентрическая 24x12 сантиметров',
    title: 'снайперка 24x12',
    size: '24x12см',
    weight: '~450 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-25sm-b.jpg',
    alt: 'снайперка / концентрическая 25 сантиметров',
    title: 'снайперка 24',
    size: '24см',
    weight: '~400 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-25sm-2-b.jpg',
    alt: 'снайперка / концентрическая 25 сантиметров',
    title: 'снайперка 25-2',
    size: '25см',
    weight: '~500 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-28x23sm-b.jpg',
    alt: 'снайперка / концентрическая 28x23 сантиметров',
    title: 'снайперка 28x23',
    size: '28x23см',
    weight: '~550 грам',
    frequency: '6кГц - 15кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-30x22sm-b.jpg',
    alt: 'снайперка / концентрическая 30x22 сантиметров',
    title: 'снайперка 30x22',
    size: '30x22см',
    weight: '~550 грам',
    frequency: '6кГц - 15кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sniper .card-container',
  },
]
const dd = [
  {
    img: 'assets/img/card/dd/dd-20sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 20 сантиметров.',
    title: 'DD 20',
    size: '20см',
    weight: '~400 грам',
    frequency: '6кГц - 15кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-23sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 23 сантиметров.',
    title: 'DD 23',
    size: '23см',
    weight: '~450 грам',
    frequency: '6кГц - 13кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-24x14sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 24x14 сантиметров.',
    title: 'DD 24x14',
    size: '24x14см',
    weight: '~350 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-25sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 25 сантиметров.',
    title: 'DD 25',
    size: '25см',
    weight: '~450 грам',
    frequency: '6кГц - 11кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-25sm-2-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 25 сантиметров.',
    title: 'DD 25-2',
    size: '25см',
    weight: '~450 грам',
    frequency: '6кГц - 12кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-25sm2-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 25 сантиметров.',
    title: 'DD 25-4',
    size: '25см',
    weight: '~450 грам',
    frequency: '6кГц - 12кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-27sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 27 сантиметров.',
    title: 'DD 27',
    size: '27см',
    weight: '~450 грам',
    frequency: '6кГц - 11кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-28sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 28 сантиметров.',
    title: 'DD 28',
    size: '28см',
    weight: '~550 грам',
    frequency: '6кГц - 10кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-32x24sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 32x24 сантиметров.',
    title: 'DD 32x24',
    size: '32x24см',
    weight: '~650 грам',
    frequency: '6кГц - 9кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-30x25sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 30x25 сантиметров.',
    title: 'DD 30x25',
    size: '30x25см',
    weight: '~650 грам',
    frequency: '6кГц - 10кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-30sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 30 сантиметров.',
    title: 'DD 30',
    size: '30см',
    weight: '~650 грам',
    frequency: '6кГц - 9кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
  {
    img: 'assets/img/card/dd/dd-30x32sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. ДД (DOUBLE D). Размер 30x32 сантиметров.',
    title: 'DD 30x32',
    size: '30x32см',
    weight: '~700 грам',
    frequency: '6кГц - 9кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#dd .card-container',
  },
]
const sd = [
  {
    img: 'assets/img/card/sd/sd-20sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Super D. Размер 20 сантиметров.',
    title: 'СД 20',
    size: '20см',
    weight: '~550 грам',
    frequency: '10кГц - 17кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sd .card-container',
  },
  {
    img: 'assets/img/card/sd/sd-30x24sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Super D. Размер 30x24 сантиметров.',
    title: 'СД 30x24',
    size: '30x24см',
    weight: '~600 грам',
    frequency: '6кГц - 13кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sd .card-container',
  },
  {
    img: 'assets/img/card/sd/sd-27sm-2.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Super D. Размер 28 сантиметров.',
    title: 'СКД 28',
    size: '28см',
    weight: '~600 грам',
    frequency: '6кГц - 14кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sd .card-container',
  },
  {
    img: 'assets/img/card/sd/sd-30sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Super D. Размер 30 сантиметров.',
    title: 'СД 30',
    size: '30см',
    weight: '~650 грам',
    frequency: '6кГц - 12кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#sd .card-container',
  },
]
const omega = [
  {
    img: 'assets/img/card/omega/20sm-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Омега. Размер 28 сантиметров.',
    title: 'омега 20',
    size: '20см',
    weight: '~550 грам',
    frequency: '6кГц - 15кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#omega .card-container',
  },
  {
    img: 'assets/img/card/omega/25sm2-b.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Омега. Размер 25 сантиметров.',
    title: 'омега 25',
    size: '25см',
    weight: '~600 грам',
    frequency: '6кГц - 15кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#omega .card-container',
  },
]
const bigFoot = [
  {
    img: 'assets/img/card/snayp/k-24x12sm.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Big Foot (Диференціал). Размер 20x24 сантиметров.',
    title: 'Big Foot 20x24',
    size: '20x24см',
    weight: '~450 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#bigFoot .card-container',
  },
  {
    img: 'assets/img/card/snayp/k-20x24.jpg',
    alt:
      'Поисковый Датчик,грунтовый датчик, катушка для металлоискателя квазар арм, фортуна м2,м3,про. Big Foot (Диференціал). Размер 20x24 сантиметров.',
    title: 'Big Foot 20x24 - 2',
    size: '20x24см',
    weight: '~350 грам',
    frequency: '6кГц - 16кГц',
    screenSensor: 'графіт',
    cable: 'до 120см',
    plug: '5 пін',
    container: '#bigFoot .card-container',
  },
]

const accessories = [
  {
    img: 'assets/img/images/coils/2021/2021-01-13-voprosy-otvety/wire7.jpg',
    alt: 'Провод, кабель для поисковый датчик, грунтовый датчик, катушка для металлоискателя квазар арм, фортуна',
    title: 'Кабель',
    cable: '100см - 120см',
    container: '#accessories .card-container',
    plug: '5 пін',
    descr:
      '4 провідники 0,35 мм. і 0,12 мм. Провідники приймальної котушки Rx - 0.12 мм. в екрані. Захисна оболонка кабелю - прозорий ПВХ 6 х 0,8мм.',
  },
]
export { concentric, dd, sd, omega, bigFoot, accessories }
